apiVersion: v1
kind: Service
metadata:
  name: rotator
  labels:
    app: rotator
    app.kubernetes.io/name: rotator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.rotator.metrics.port | default 9102 }}"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: rotator
  ports:
    - name: http
      port: {{ .Values.rotator.metrics.port | default 9102 }}
      targetPort: {{ .Values.rotator.metrics.port | default 9102 }}
      protocol: TCP

