apiVersion: v1
kind: Service
metadata:
  name: rotator
  labels:
    app: rotator
    app.kubernetes.io/name: rotator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: rotator
  ports:
    - name: http
      port: 9102
      targetPort: 9102
      protocol: TCP

